name: acm_sigmetrics
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - atk-1.0=2.36.0=ha1a6a79_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.10.11=h06a4308_0
  - cairo=1.16.0=h19f5f5c_2
  - certifi=2022.9.24=py310h06a4308_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.13.1=hef1e5e3_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gdk-pixbuf=2.42.8=h433bba3_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gobject-introspection=1.72.0=py310hbb6d50b_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h3cd0ef9_0
  - gtk2=2.24.33=h73c1081_2
  - gts=0.7.6=hb67d8dd_3
  - harfbuzz=4.3.0=hd55b92a_0
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgd=2.3.3=h695aa2c_1
  - libgomp=11.2.0=h1234567_1
  - libpng=1.6.37=hbc83047_0
  - librsvg=2.54.4=h19fe530_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.4.0=hecacb30_1
  - libtool=2.4.6=h295c915_1008
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib-base=3.5.3=py310hf590b9c_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h5eee18b_3
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numexpr=2.8.3=py310hcea2de6_0
  - numpy-base=1.23.3=py310h8e6c178_1
  - openssl=1.1.1s=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.4=py310h6a678d5_0
  - pango=1.50.7=h05da053_0
  - pcre=8.45=h295c915_0
  - pip=22.2.2=py310h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pyparsing=3.0.9=py310h06a4308_0
  - python=3.10.6=haa1d7c7_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2022.1=py310h06a4308_0
  - readline=8.2=h5eee18b_0
  - seaborn=0.12.0=py310h06a4308_0
  - setuptools=65.5.0=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2022f=h04d1e81_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.1.0
    - attrs==22.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cffi==1.15.1
    - contourpy==1.0.6
    - cvxpy==1.2.2
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - ecos==2.0.10
    - entrypoints==0.4
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - fonttools==4.38.0
    - idna==3.4
    - ipykernel==6.17.1
    - ipython==8.6.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - jsonschema==4.17.0
    - jupyter==1.0.0
    - jupyter-client==7.4.5
    - jupyter-console==6.4.4
    - jupyter-core==5.0.0
    - jupyter-server==1.23.1
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.4.4
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - nbclassic==0.4.8
    - nbclient==0.7.0
    - nbconvert==7.2.4
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - networkx==2.8.8
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numpy==1.23.4
    - osqp==0.6.2.post5
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.3.0
    - platformdirs==2.5.3
    - prometheus-client==0.15.0
    - prompt-toolkit==3.0.32
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pydot==1.4.2
    - pygments==2.13.0
    - pyrsistent==0.19.2
    - python-graphviz==0.20.1
    - pyzmq==24.0.1
    - qdldl==0.1.5.post2
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - scipy==1.9.3
    - scs==3.2.2
    - send2trash==1.8.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.6.0
    - terminado==0.17.0
    - tinycss2==1.2.1
    - tornado==6.2
    - traitlets==5.5.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - widgetsnbextension==4.0.3
prefix: `/user/tsisalem/home/anaconda3/envs/acm_sigmetrics`
